server:
  port: 9090

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/product/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://auth.uzgps.uz:8443/auth/realms/spring-realm
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak
            client-id: api-gateway
            client-secret: jM35k5hTECVQJee4s7s8gK7zRfoj5YS4
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
